name: Code health checks

on: [push, pull_request]

env:
  CODECHECK_PY_VER: '3.10'

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python-${{ env.CODECHECK_PY_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.CODECHECK_PY_VER }}
      - name: Install dependencies
        run: |
          ./docker/pip_deps.sh --extra-requirements="codecheck-requirements.txt"
      - name: Run pylint
        run: |
          ./test/codecheck/pylint.sh

  pytype:
    name: Pytype
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python-${{ env.CODECHECK_PY_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.CODECHECK_PY_VER }}
      - name: Install dependencies
        run: |
          ./docker/pip_deps.sh --extra-requirements="codecheck-requirements.txt"
      - name: Run pytype
        run: |
          PYTHONPATH=. pytype --config setup.cfg chewie
